server:
  port: 8081
  servlet:
    context-path: /food

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ""
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
